package com.example.assignment3_recipeapp.room.user

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Entity class for storing user information in the database.
 * This class represents the schema of the User table within the Room Database.
 */
@Entity
data class User(
    @PrimaryKey(autoGenerate = true)
    val uid: Long = 0L, // Unique identifier for the user, auto-generated by the database.
    val username: String, // User's chosen username.
    val name: String, // User's first name.
    val surname: String, // User's last name.
    val email: String, // User's email address.
    val gender: String, // User's gender.
    val dateOfBirth: String, // User's date of birth.
    val password: String, // User's password for login authentication.
    val role: String, // Role of the user within the system (e.g., 'admin', 'user').
    val registrationDate: String?, // Date when the user registered. Optional and can be nullable.
    val profilePictureUrl: String? // URL to the user's profile picture. Optional and can be nullable.
)